### ISSUE TITLE
buildbot status

### ISSUE THREAD

**Issue by udeved** [cromnix/artools#4]
@aadityabagga 

I think buildpkg is ready  for cromnix. What's the status on the buildbot front?
Would you mind to have a test with it once we have rebuild cromnix-dev pkgs and updated repo?

Would it help if build lists reflected the packages subfolder structure?

eg 

`buildpkg -p main`

builds all pkgs in main.

**Comment by aadityabagga** [comment]
Hi @udeved,

Current travis-ci based buildbot is ready for testing, should I port it to https://github.com/cromnix/packages (it uses manjaro unstable branch to bootstrap, is that ok)? [referance](https://github.com/manjaro/packages-openrc/pull/55/files)

After working with it for about a week now, I think it has a fatal flaw, especially if we are building large number of packages: travis-ci.org only allows the bot to run for 50 minutes and after that terminates it; and since we will probably be building a lot of packages this can be an issue ([example](https://travis-ci.org/aadityabagga/packages-community/builds/244367413?utm_source=github_status&utm_medium=notification)).

The solution as far as I can see is to use something like [jenkins](https://jenkins.io/) or [buildbot](http://buildbot.net/) on a dedicated server for building and deploying, but that would require money..

To work around this we could change small number of packages, or create pull requests for each set of packages.

What do you guys think?

**Comment by cromerc** [comment]
I don't think that it using manjaro to bootstrap cromnix will cause any problems, I bootstrapped cromnix from arch linux just fine so I would assume that manjaro shouldn't have any issues either. As far as porting it, yes we do need some implementation to help us build packages and deploy.

The 50 minutes is a real bummer, but as long as we only commit small batches of packages at a time it shouldn't be a problem.

Maybe in the future once the project is stable we might be able to buy a real build server, but that will be way down the road from now.

**Comment by udeved** [comment]
@aadityabagga 

If you want, go ahead with cromnix package tree, but I think the SF hosting is not sufficient to handle it. For testing purposes, would be great, realistically, we may need a fast mirror to use it effectively. I notice SF connections are partially timing out when pacman syncs repos, SF hosting can't handle fast successive requests it seems. so this may be a problem, if the travis build fails due to slow response from SF when pulling depend packages.

**Comment by aadityabagga** [comment]
Ok, will give it a try guys.

Will port the arch-openrc build bot to cromnix/packages (since it has custom repo support), and then look to integrating the deployment to a test sourceforge repo.

Time required: 1-2 days.

**Comment by aadityabagga** [comment]
Have submitted an initial pull request in which the build bot was able to build and deploy the packages, it can be merged after more testing.

https://github.com/cromnix/packages/pull/6

https://travis-ci.org/aadityabagga/packages/builds/246712372

**Comment by aadityabagga** [comment]
Happy to report that it survived building and deploying of a large number of packages, summary of which is:
~~~~
$ .travis/scripts/report_build_status.sh
packages attempted: 26
main/pam
main/pambase
misc/arch-compat
misc/eudev
misc/mkinitcpio
misc/mkinitcpio-nfs-utils
openrc/eudev-openrc
openrc/netifrc
openrc/openrc
openrc/openrc-accessible
openrc/openrc-base
openrc/openrc-desktop
openrc/openrc-devel
openrc/openrc-misc
openrc/openrc-net
openrc/openrc-settingsd
openrc/openrc-video
openrc/opensysusers
openrc/opentmpfiles
session-tracking/accountsservice-elogind
session-tracking/dbus-elogind
session-tracking/elogind
session-tracking/polkit-elogind
session-tracking/procps-ng-elogind
session-tracking/sddm-elogind
session-tracking/udisks2-elogind
packages failed: 8
misc/mkinitcpio
openrc/netifrc
openrc/openrc-desktop
openrc/openrc-misc
openrc/openrc-net
openrc/opentmpfiles
session-tracking/sddm-elogind
session-tracking/udisks2-elogind
~~~~
Different packages failed to build for different reasons.
Logs are available [here](https://api.travis-ci.org/jobs/246726655/log.txt?deansi=true) and
built packages are available [here](https://sourceforge.net/projects/mefiles/files/Manjaro/test/cromnix/packages/x86_64/).
